<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IL-1270" name="com.deere.testCases.US24253_ISG_CaseCodingAction" tests="1" failures="0" timestamp="23 May 2018 06:22:03 GMT" time="111.415" errors="1">
  <testcase name="test_ISGCaseCodingScreenDetails" time="111.415" classname="com.deere.testCases.US24253_ISG_CaseCodingAction">
    <error type="java.lang.AssertionError" message="Login to Site Minder Site is Unsuccessful expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login to Site Minder Site is Unsuccessful expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.deere.global.CommonFunctions.assertTrue(CommonFunctions.java:1083)
	at com.deere.testCases.US24253_ISG_CaseCodingAction.test_ISGCaseCodingScreenDetails(US24253_ISG_CaseCodingAction.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test_ISGCaseCodingScreenDetails -->
</testsuite> <!-- com.deere.testCases.US24253_ISG_CaseCodingAction -->
